# Generated by Django 3.1.5 on 2021-03-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='is_support',
            field=models.BooleanField(default=False),
        ),
    ]
