# Generated by Django 3.1.5 on 2021-03-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_usermessage_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='content',
            field=models.TextField(verbose_name='Message content'),
        ),
    ]
