# Generated by Django 3.1.5 on 2021-03-20 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0006_auto_20210320_1456'),
        ('messaging', '0004_auto_20210319_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.mission'),
        ),
    ]
