# Generated by Django 3.1.5 on 2021-03-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, verbose_name='Mission status label')),
            ],
            options={
                'verbose_name': 'Mission status',
                'verbose_name_plural': 'Mission status',
                'db_table': 'mission_ref_mission_status',
            },
        ),
    ]
