# Generated by Django 3.1.5 on 2021-03-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, verbose_name='Mission category label')),
                ('base_reward_amount', models.SmallIntegerField(verbose_name='Mission category base reward')),
            ],
            options={
                'verbose_name': 'Mission category',
                'verbose_name_plural': 'Mission categories',
                'db_table': 'mission_ref_mission_category',
            },
        ),
    ]
