# Generated by Django 3.1.5 on 2021-03-19 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mission', '0002_missioncategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionBonusReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_amount', models.SmallIntegerField(verbose_name='Mission bonus reward amount')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mission bonus reward description')),
            ],
            options={
                'verbose_name': 'Mission bonus reward',
                'verbose_name_plural': 'Mission bonus rewards',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mission creation date')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Mission update date')),
                ('title', models.CharField(max_length=50, verbose_name='Mission title')),
                ('description', models.CharField(max_length=255, verbose_name='Mission description')),
                ('acceptor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptor_user', to=settings.AUTH_USER_MODEL)),
                ('bearer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bearer_user', to=settings.AUTH_USER_MODEL)),
                ('bonus_reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mission.missionbonusreward')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mission.missioncategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mission.missionstatus')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
            },
        ),
    ]
