# Generated by Django 3.1.5 on 2021-03-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0004_auto_20210319_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionbonusreward',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Mission bonus reward description'),
        ),
        migrations.AlterModelTable(
            name='missionbonusreward',
            table='mission_bonus_reward',
        ),
    ]
