# Generated by Django 3.1.5 on 2021-03-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0005_auto_20210320_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='acceptor_validate',
            field=models.BooleanField(default=False, verbose_name='Acceptor user validate mission finish'),
        ),
        migrations.AddField(
            model_name='mission',
            name='bearer_validate',
            field=models.BooleanField(default=False, verbose_name='Bearer user validate mission finish'),
        ),
    ]
