# Generated by Django 3.1.5 on 2021-03-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0006_auto_20210320_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='missioncategory',
            name='xp_amount',
            field=models.IntegerField(default=10, verbose_name='Mission category base reward'),
            preserve_default=False,
        ),
    ]
