# Generated by Django 3.1.5 on 2021-04-03 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0007_missioncategory_xp_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Mission update date'),
        ),
    ]
