# Generated by Django 3.1.5 on 2021-02-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
    ]
