# Generated by Django 3.1.5 on 2021-02-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210219_1331'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usertype',
            table='user_ref_user_type',
        ),
    ]
