# Generated by Django 3.1.5 on 2021-02-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210222_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='id_type',
            new_name='document_type',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='id_user',
            new_name='user',
        ),
    ]
