# Generated by Django 3.1.5 on 2021-02-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210223_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
