# Generated by Django 3.1.5 on 2021-03-09 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210226_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Document creation date'),
        ),
    ]
