# Generated by Django 3.1.5 on 2021-04-03 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Product label')),
                ('price', models.SmallIntegerField(verbose_name='Product price')),
                ('xp_amount', models.IntegerField(null=True, verbose_name='Product xp amount')),
                ('path_to_sprite', models.CharField(max_length=150, null=True, verbose_name='Product path to sprite')),
                ('is_multiple', models.BooleanField(default=False, verbose_name='Product can be bought multiple times')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mission creation date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopping.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product transaction',
                'verbose_name_plural': 'Product transactions',
            },
        ),
    ]
