# Generated by Django 3.1.5 on 2021-04-03 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='path_to_sprite',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Product path to sprite'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transaction creation date'),
        ),
    ]
