# Generated by Django 3.1.5 on 2021-04-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20210403_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='default_desc', verbose_name='Product description'),
            preserve_default=False,
        ),
    ]
