# Generated by Django 3.1.5 on 2021-04-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_product_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producttransaction',
            table='shopping_product_transaction',
        ),
    ]
